### ISSUE TITLE
Link to the presentation is broken

### ISSUE THREAD

**Issue by shcheklein** [peopledoc/mlvtools-tutorial#11]
Hey, folks! Looks like https://peopledoc.github.io/mlv-tools-tutorial/talks/pyData/presentation.html link in the README is broken. Have you moved it somewhere?

**Comment by elemoine** [comment]
Use https://peopledoc.github.io/mlvtools-tutorial/talks/pyData/presentation.html.
This, and other things, are being fixed with #10.

**Comment by shcheklein** [comment]
thanks @elemoine 🙏
